# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180613_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='enum',
            field=models.IntegerField(choices=[(0, ''), (1, 'pass'), (2, 'no pass'), (3, 'absence')], default=0),
        ),
    ]
