# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-15 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_auto_20190316_0226'),
        ('courses', '0014_auto_20190209_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCommonProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.Problem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topiccommonproblem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='common_problems',
            field=models.ManyToManyField(blank=True, through='courses.TopicCommonProblem', to='problems.Problem'),
        ),
    ]
