# Generated by Django 2.2.9 on 2020-01-31 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190316_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='extra_requirements_ok',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='enable_queues',
            field=models.BooleanField(blank=True, default=False, verbose_name='enable electronic queues'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enable_sheet',
            field=models.BooleanField(blank=True, default=False, verbose_name='enable mark sheet'),
        ),
        migrations.AlterField(
            model_name='mailthread',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailthread',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.Problem'),
        ),
        migrations.AlterField(
            model_name='mailthread',
            name='resolved',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='queue is active'),
        ),
        migrations.AlterField(
            model_name='topiccommonproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_topic', to='problems.Problem'),
        ),
    ]
