# Generated by Django 2.2.9 on 2020-06-24 00:20

from django.db import migrations
import django.db.models.deletion
import users.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userfolder_users'),
        ('courses', '0016_auto_20200201_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=users.modelfields.OwnerGroupField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.AdminGroup', verbose_name='owner'),
        ),
    ]
