# Generated by Django 2.2.9 on 2020-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_teacher_all_solutions_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_all_solutions_access',
            field=models.IntegerField(choices=[(0, 'no access'), (10, 'view current solution state'), (20, 'view compilation log'), (30, 'view source code'), (40, 'view testing details on sample tests'), (50, 'view testing details'), (60, 'view testing details with checker messages'), (70, 'view testing details and test data')], default=10, verbose_name='student’s access to all solutions of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_own_solutions_access',
            field=models.IntegerField(choices=[(0, 'no access'), (10, 'view current solution state'), (20, 'view compilation log'), (30, 'view source code'), (40, 'view testing details on sample tests'), (50, 'view testing details'), (60, 'view testing details with checker messages'), (70, 'view testing details and test data')], default=50, verbose_name='student’s access to his own solutions'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_all_solutions_access',
            field=models.IntegerField(choices=[(0, 'no access'), (10, 'view current solution state'), (20, 'view compilation log'), (30, 'view source code'), (40, 'view testing details on sample tests'), (50, 'view testing details'), (60, 'view testing details with checker messages'), (70, 'view testing details and test data')], default=60, verbose_name='teacher’s access to all solutions of the course'),
        ),
    ]
