# Generated by Django 2.2.9 on 2020-07-05 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20200627_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='problem_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.ProblemFolder', verbose_name='problem folder'),
        ),
    ]
