# Generated by Django 3.1.2 on 2022-02-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_private_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stop_on_fail',
            field=models.BooleanField(blank=True, default=False, verbose_name='stop after first failed test'),
        ),
    ]
