# Generated by Django 3.1.2 on 2022-02-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_course_stop_on_fail'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='overdue_factor',
            field=models.FloatField(default=0.5, verbose_name='overdue factor'),
        ),
    ]
