# Generated by Django 3.1.2 on 2022-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_topic_overdue_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='max_size',
            field=models.PositiveIntegerField(default=0, verbose_name='maximum size'),
        ),
    ]
