image: python:3.8

pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - cd project
          - export DJANGO_SETTINGS_MODULE="irunner2.settings_dev"
          - python manage.py test
