# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Short Latin name to use in page links', unique=True, verbose_name='name for URL')),
                ('local_name', models.CharField(blank=True, max_length=100, verbose_name='name in local language')),
                ('en_name', models.CharField(blank=True, max_length=100, verbose_name='name in English')),
                ('local_description', models.TextField(blank=True, verbose_name='descripion in local language')),
                ('en_description', models.TextField(blank=True, verbose_name='descripion in English')),
                ('is_registration_available', models.BooleanField(default=False, verbose_name='registration is available')),
            ],
        ),
    ]
