# Generated by Django 2.2.9 on 2020-01-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_registration_available',
            field=models.BooleanField(blank=True, default=False, verbose_name='registration is available'),
        ),
    ]
