# Generated by Django 2.2.9 on 2020-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200201_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_mode',
            field=models.IntegerField(choices=[(1, 'Coach and teams'), (2, 'Individual')], default=1, verbose_name='registration mode'),
        ),
    ]
