# Generated by Django 2.2.9 on 2020-05-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_registration_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fill_forms_in_en',
            field=models.BooleanField(default=True, verbose_name='the forms are filled in English'),
        ),
    ]
