# Generated by Django 2.2.9 on 2020-09-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_varbinary'),
        ('events', '0004_event_fill_forms_in_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.FileMetadata', verbose_name='image file'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo_style',
            field=models.IntegerField(blank=True, choices=[(1, 'File'), (2, 'ICPC')], default=None, null=True, verbose_name='logo style'),
        ),
    ]
