# Generated by Django 2.2.9 on 2020-09-16 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200904_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Short Latin name to use in page links', unique=True, verbose_name='name for URL')),
                ('when', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('is_public', models.BooleanField(blank=True, default=True, verbose_name='show on the main page')),
                ('local_name', models.CharField(blank=True, max_length=100, verbose_name='name in local language')),
                ('en_name', models.CharField(blank=True, max_length=100, verbose_name='name in English')),
                ('local_content', models.TextField(blank=True, verbose_name='descripion in local language')),
                ('en_content', models.TextField(blank=True, verbose_name='descripion in English')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
