# Generated by Django 2.2.9 on 2020-09-22 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200922_0412'),
        ('contests', '0012_auto_20200627_1745'),
        ('events', '0006_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_create_users',
            field=models.BooleanField(blank=True, default=False, verbose_name='create users automatically'),
        ),
        migrations.AddField(
            model_name='event',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.Contest', verbose_name='Contest'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_created_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='password_generation_algo',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='user_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserFolder', verbose_name='user folder'),
        ),
        migrations.AddField(
            model_name='event',
            name='username_pattern',
            field=models.CharField(blank=True, max_length=30, verbose_name='username pattern'),
        ),
        migrations.AlterField(
            model_name='page',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
