# Generated by Django 3.1.2 on 2021-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200922_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_mode',
            field=models.IntegerField(choices=[(1, 'Coach and teams'), (2, 'Individual'), (3, 'Individual school')], default=1, verbose_name='registration mode'),
        ),
    ]
