# Generated by Django 3.1.2 on 2022-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210505_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='Short Latin name to use in page links', verbose_name='name for URL'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('event', 'slug')},
        ),
    ]
