# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-30 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proglangs', '0003_auto_20160708_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('pas', 'Pascal'), ('dpr', 'Delphi'), ('py', 'Python'), ('cs', 'C#'), ('sh', 'Shell')], default='', max_length=8, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='compilerdetails',
            name='compile_command',
            field=models.CharField(blank=True, max_length=1023, verbose_name='compile command'),
        ),
        migrations.AlterField(
            model_name='compilerdetails',
            name='run_command',
            field=models.CharField(blank=True, max_length=1023, verbose_name='run command'),
        ),
    ]
