# Generated by Django 2.2.9 on 2020-06-27 13:40

from django.db import migrations
from django.db.models import Case, Value, When, F


def _remap(model, field):
    model.objects.update(**{field: Case(
        When(then=Value(10), **{field: 1}),
        When(then=Value(20), **{field: 2}),
        When(then=Value(30), **{field: 3}),
        When(then=Value(40), **{field: 7}),
        When(then=Value(50), **{field: 4}),
        When(then=Value(60), **{field: 5}),
        When(then=Value(70), **{field: 6}),
        default=F(field)
    )})


def remap_enums(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    _remap(Course, 'student_own_solutions_access')
    _remap(Course, 'student_all_solutions_access')
    _remap(Course, 'teacher_all_solutions_access')

    Contest = apps.get_model('contests', 'Contest')
    _remap(Contest, 'contestant_own_solutions_access')


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0013_varbinary'),
        ('courses', '0018_course_teacher_all_solutions_access'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remap_enums),
    ]
