# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcpcCoach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='e-mail')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('university', models.CharField(max_length=50, verbose_name='university')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='IcpcContestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('study_program', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('SPECIALIST', 'Specialist'), ('MASTER', 'Master'), ('PHD', 'PhD')], max_length=16, verbose_name='study program')),
                ('program_start_year', models.IntegerField(verbose_name='program start year')),
                ('graduation_year', models.IntegerField(verbose_name='graduation year')),
                ('sex', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=16, verbose_name='sex')),
            ],
        ),
        migrations.CreateModel(
            name='IcpcTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='team name')),
                ('participation_venue', models.CharField(choices=[('OWN', 'Own university'), ('BSU', 'Belarusian State University'), ('NEARBY', 'Ask about near venues')], max_length=16, verbose_name='participation venue')),
                ('participation_type', models.CharField(choices=[('OFFICIAL', 'Official (diplomas, personal invitation)'), ('HORS_CONCOURS', 'Hors concours')], max_length=16, verbose_name='participation type')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.IcpcCoach')),
            ],
        ),
        migrations.AddField(
            model_name='icpccontestant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.IcpcTeam'),
        ),
    ]
