# Generated by Django 2.2.9 on 2020-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200201_0255'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpccoach',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='e-mail'),
        ),
        migrations.AlterUniqueTogether(
            name='icpccoach',
            unique_together={('event', 'email')},
        ),
    ]
