# Generated by Django 2.2.9 on 2020-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200416_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='icpccoach',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='icpccoach',
            name='group',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Group number'),
        ),
        migrations.AddField(
            model_name='icpccoach',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of study'),
        ),
    ]
