# Generated by Django 2.2.9 on 2020-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_icpccoach_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpccoach',
            name='faculty',
            field=models.CharField(blank=True, max_length=120, verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='icpccoach',
            name='university',
            field=models.CharField(max_length=120, verbose_name='university'),
        ),
    ]
