# Generated by Django 3.1.2 on 2021-05-05 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_createduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='icpccoach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='\\+\\d{7,15}')], verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='icpccoach',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Postal address'),
        ),
    ]
