# Generated by Django 3.1.2 on 2022-06-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210505_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='icpccoach',
            name='achievements',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Achievements'),
        ),
        migrations.AddField(
            model_name='icpccoach',
            name='country',
            field=models.CharField(blank=True, max_length=32, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='icpccoach',
            name='extra_info',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Extra information'),
        ),
    ]
