# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiztemplate_score_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='score_policy',
            field=models.IntegerField(choices=[(0, 'Soft'), (1, 'Strict')], default=1, verbose_name='score policy'),
        ),
    ]
