# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quizsession_score_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='score_policy',
            field=models.IntegerField(choices=[(0, 'soft'), (1, 'strict')], default=1, verbose_name='score policy'),
        ),
        migrations.AlterField(
            model_name='quiztemplate',
            name='score_policy',
            field=models.IntegerField(choices=[(0, 'soft'), (1, 'strict')], default=1, verbose_name='score policy'),
        ),
    ]
