# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quizsession_pending_manual_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquestionanswer',
            name='user_answer',
            field=models.CharField(default=None, max_length=16383, null=True),
        ),
    ]
