# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_quizsession_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinstance',
            name='enable_discussion',
            field=models.BooleanField(default=False, verbose_name='enable discussion'),
        ),
    ]
