# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-23 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0014_quizinstance_enable_discussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSessionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16383)),
                ('timestamp', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizSession')),
            ],
        ),
    ]
