# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-23 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_quizsessioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinstance',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quizinstance',
            name='disable_time_limit',
            field=models.BooleanField(default=False, verbose_name='disable time limit'),
        ),
    ]
