# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_auto_20190423_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinstance',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
