# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-24 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_auto_20190423_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='quizsessioncomment',
            name='text',
            field=models.TextField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='sessionquestionanswer',
            name='user_answer',
            field=models.TextField(default=None, max_length=65535, null=True),
        ),
    ]
