# Generated by Django 2.2.9 on 2020-03-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_auto_20200201_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinstance',
            name='show_answers',
            field=models.BooleanField(default=False, verbose_name='show answers'),
        ),
        migrations.AlterField(
            model_name='quiztemplate',
            name='attempts',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='attempts'),
        ),
    ]
