# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-15 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20181214_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemrelatedfile',
            name='file_type',
            field=models.IntegerField(choices=[(211, 'TeX statement (TeXtoHTML)'), (224, 'TeX statement (pylightex)'), (212, 'HTML statement'), (213, 'Additional statement file'), (214, 'Solution description'), (220, 'Sample input file'), (221, 'Sample output file'), (222, 'User file')], verbose_name='file type'),
        ),
    ]
