# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_auto_20190316_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemextrainfo',
            name='allowed_programming_languages',
            field=models.CharField(blank=True, max_length=255, verbose_name='allowed programming languages'),
        ),
    ]
