# Generated by Django 2.2.9 on 2020-01-31 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_problemextrainfo_allowed_programming_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemrelatedsourcefile',
            name='compiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proglangs.Compiler', verbose_name='compiler'),
        ),
    ]
