# Generated by Django 2.2.9 on 2020-02-21 00:36

from django.db import migrations

from storage.resource_id import ResourceIdField


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_auto_20200201_0255'),
    ]

    operations = [
        migrations.AlterField('ProblemRelatedFile', 'resource_id', ResourceIdField()),
        migrations.AlterField('ProblemRelatedSourceFile', 'resource_id', ResourceIdField()),
        migrations.AlterField('TestCase', 'input_resource_id', ResourceIdField()),
        migrations.AlterField('TestCase', 'answer_resource_id', ResourceIdField()),
        migrations.AlterField('TestCaseValidation', 'input_resource_id', ResourceIdField()),
    ]
