# Generated by Django 2.2.9 on 2020-09-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_problemfolderaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemextrainfo',
            name='check_plagiarism',
            field=models.BooleanField(blank=True, default=True, verbose_name='Check plagiarism'),
        ),
        migrations.AlterField(
            model_name='problemaccess',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Read'), (2, 'Modify'), (3, 'Write')]),
        ),
        migrations.AlterField(
            model_name='problemfolderaccess',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Read'), (2, 'Modify'), (3, 'Write')]),
        ),
    ]
