# Generated by Django 3.1.2 on 2021-07-05 23:36

import common.locales.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_auto_20200927_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemrelatedfile',
            name='language',
            field=common.locales.fields.LanguageField(blank=True, max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='problemfolder',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problemfolder',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problemfolder',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problemrelatedfile',
            name='file_type',
            field=models.IntegerField(choices=[(211, 'TeX statement (TeXtoHTML)'), (224, 'TeX statement (pylightex)'), (212, 'HTML statement'), (213, 'Additional statement file'), (225, 'Problem tutorial (pylightex)'), (214, 'Solution description'), (220, 'Sample input file'), (221, 'Sample output file'), (222, 'User file')], verbose_name='file type'),
        ),
    ]
