# Generated by Django 2.2.9 on 2020-01-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_contest_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='enable_printing',
            field=models.BooleanField(blank=True, default=False, verbose_name='enable printing'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='enable_upsolving',
            field=models.BooleanField(blank=True, default=False, verbose_name='enable upsolving after the end of the contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rules',
            field=models.IntegerField(choices=[(1, 'ACM'), (2, 'IOI')], default=1, verbose_name='rules'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='show_pending_runs',
            field=models.BooleanField(blank=True, default=True, verbose_name='show pending runs during the freeze time'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='unfreeze_standings',
            field=models.BooleanField(blank=True, default=False, verbose_name='unfreeze standings after the end of the contest'),
        ),
    ]
