# Generated by Django 3.1.2 on 2021-10-29 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20211029_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='attempt_limit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='number of attempts per problem...'),
        ),
        migrations.AddField(
            model_name='contest',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(0, 600), verbose_name='...during the time period'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='total_attempt_limit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='maximum total number of attempts per problem'),
        ),
    ]
