# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180603_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_api_access',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_access_to_problems',
            field=models.BooleanField(default=False, verbose_name='user was explicitly granted access to certain problems'),
        ),
    ]
