# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-05 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181215_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_access_to_quizzes',
            field=models.BooleanField(default=False, verbose_name='user was explicitly granted access to certain quiz categories'),
        ),
    ]
