# Generated by Django 2.2.9 on 2020-02-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_varbinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_access_to_admin',
            field=models.BooleanField(default=False, verbose_name='user has access to administrative sections'),
        ),
    ]
