# Generated by Django 2.2.9 on 2020-06-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userfolder_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_access_to_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_access_to_problems',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_access_to_quizzes',
        ),
    ]
