# Generated by Django 2.2.9 on 2020-09-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200624_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolderaccess',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Read'), (2, 'Modify'), (3, 'Write')]),
        ),
    ]
