# Generated by Django 2.2.9 on 2020-02-21 00:41

from django.db import migrations

from storage.storage import ResourceIdField


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20160306_1931'),
    ]

    operations = [
        migrations.AlterField('FileMetadata', 'resource_id', ResourceIdField()),
    ]
