# Generated by Django 2.2.9 on 2020-01-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmessage',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, verbose_name='show on the main page'),
        ),
    ]
